import 'dart:ui';
import '../../data/models/achievement.dart';

Color getTierColor(AchievementTier tier) {
  switch (tier) {
    case AchievementTier.bronze:
      return const Color(0xFFCD7F32);
    case AchievementTier.silver:
      return const Color(0xFFC0C0C0);
    case AchievementTier.gold:
      return const Color(0xFFFFD700);
    case AchievementTier.platinum:
      return const Color(0xFFE5E4E2);
  }
}

final achievementsCatalog = [
  // Bronze tier - Sessions
  AchievementDefinition(
    id: 'first_flow',
    title: 'First Focus',
    description: 'Complete 1 session',
    icon: '🎯',
    tier: AchievementTier.bronze,
    requirementType: RequirementType.totalSessions,
    requirementValue: 1,
    isUnlocked: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions >= 1,
    getProgress: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions,
  ),
  AchievementDefinition(
    id: 'flow_starter',
    title: 'Getting Started',
    description: 'Complete 5 sessions',
    icon: '⚡',
    tier: AchievementTier.bronze,
    requirementType: RequirementType.totalSessions,
    requirementValue: 5,
    isUnlocked: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions >= 5,
    getProgress: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions,
  ),
  AchievementDefinition(
    id: '10_hours',
    title: '10 Hours',
    description: '600 total focus minutes',
    icon: '⏰',
    tier: AchievementTier.bronze,
    requirementType: RequirementType.totalMinutes,
    requirementValue: 600,
    isUnlocked: (_, __, ___, totalMinutes, ____, _____, ______, _______, ________, _________, __________) => totalMinutes >= 600,
    getProgress: (_, __, ___, totalMinutes, ____, _____, ______, _______, ________, _________, __________) => totalMinutes,
  ),
  AchievementDefinition(
    id: 'quick_win',
    title: 'Quick Win',
    description: 'Complete 10 Quick Win sessions',
    icon: '🚀',
    tier: AchievementTier.bronze,
    requirementType: RequirementType.quickWinSessions,
    requirementValue: 10,
    isUnlocked: (_, __, ___, ____, _____, ______, quickSessions, _______, ________, _________, __________) => quickSessions >= 10,
    getProgress: (_, __, ___, ____, _____, ______, quickSessions, _______, ________, _________, __________) => quickSessions,
  ),

  // Silver tier
  AchievementDefinition(
    id: 'productivity_machine',
    title: 'Task Crusher',
    description: 'Complete 20 tasks',
    icon: '💪',
    tier: AchievementTier.silver,
    requirementType: RequirementType.totalTasks,
    requirementValue: 20,
    isUnlocked: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks >= 20,
    getProgress: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks,
  ),
  AchievementDefinition(
    id: 'pomodoro_pro',
    title: 'Pomodoro Pro',
    description: 'Complete 10 Pomodoro sessions',
    icon: '🍅',
    tier: AchievementTier.silver,
    requirementType: RequirementType.pomodoroSessions,
    requirementValue: 10,
    isUnlocked: (_, __, ___, ____, _____, pomodoroSessions, ______, _______, ________, _________, __________) => pomodoroSessions >= 10,
    getProgress: (_, __, ___, ____, _____, pomodoroSessions, ______, _______, ________, _________, __________) => pomodoroSessions,
  ),
  AchievementDefinition(
    id: 'deep_worker',
    title: 'Deep Worker',
    description: 'Complete 5 Deep Work sessions',
    icon: '🧠',
    tier: AchievementTier.silver,
    requirementType: RequirementType.deepWorkSessions,
    requirementValue: 5,
    isUnlocked: (_, __, ___, ____, deepSessions, _____, ______, _______, ________, _________, __________) => deepSessions >= 5,
    getProgress: (_, __, ___, ____, deepSessions, _____, ______, _______, ________, _________, __________) => deepSessions,
  ),
  AchievementDefinition(
    id: 'streak_starter',
    title: 'Streak Starter',
    description: 'Achieve a 3-day streak',
    icon: '🔥',
    tier: AchievementTier.silver,
    requirementType: RequirementType.currentStreak,
    requirementValue: 3,
    isUnlocked: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak >= 3,
    getProgress: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak,
  ),
  AchievementDefinition(
    id: 'week_warrior',
    title: 'Week Warrior',
    description: 'Achieve a 7-day streak',
    icon: '🏆',
    tier: AchievementTier.silver,
    requirementType: RequirementType.currentStreak,
    requirementValue: 7,
    isUnlocked: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak >= 7,
    getProgress: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak,
  ),
  AchievementDefinition(
    id: 'energy_explorer',
    title: 'Energy Explorer',
    description: 'Use all 4 energy ratings',
    icon: '⚡',
    tier: AchievementTier.silver,
    requirementType: RequirementType.energyRatings,
    requirementValue: 4,
    isUnlocked: (_, __, ___, ____, _____, ______, _______, energyRatings, ________, _________, __________) => energyRatings.length >= 4,
    getProgress: (_, __, ___, ____, _____, ______, _______, energyRatings, ________, _________, __________) => energyRatings.length,
  ),
  AchievementDefinition(
    id: 'note_taker',
    title: 'Note Taker',
    description: 'Create 10 notes',
    icon: '📝',
    tier: AchievementTier.bronze,
    requirementType: RequirementType.notesCreated,
    requirementValue: 10,
    isUnlocked: (_, __, ___, ____, _____, ______, _______, ________, notesCount, _________, __________) => notesCount >= 10,
    getProgress: (_, __, ___, ____, _____, ______, _______, ________, notesCount, _________, __________) => notesCount,
  ),
  AchievementDefinition(
    id: 'template_creator',
    title: 'Template Creator',
    description: 'Save 3 templates',
    icon: '🧩',
    tier: AchievementTier.bronze,
    requirementType: RequirementType.templatesSaved,
    requirementValue: 3,
    isUnlocked: (_, __, ___, ____, _____, ______, _______, ________, _________, templatesCount, __________) => templatesCount >= 3,
    getProgress: (_, __, ___, ____, _____, ______, _______, ________, _________, templatesCount, __________) => templatesCount,
  ),

  // Gold tier
  AchievementDefinition(
    id: 'flow_regular',
    title: 'Flow Regular',
    description: 'Complete 20 sessions',
    icon: '💫',
    tier: AchievementTier.gold,
    requirementType: RequirementType.totalSessions,
    requirementValue: 20,
    isUnlocked: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions >= 20,
    getProgress: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions,
  ),
  AchievementDefinition(
    id: 'task_master',
    title: 'Task Master',
    description: 'Complete 25 tasks',
    icon: '👑',
    tier: AchievementTier.gold,
    requirementType: RequirementType.totalTasks,
    requirementValue: 25,
    isUnlocked: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks >= 25,
    getProgress: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks,
  ),
  AchievementDefinition(
    id: '1000_minutes',
    title: '1000 Minutes',
    description: '1,000 total focus minutes',
    icon: '🌟',
    tier: AchievementTier.gold,
    requirementType: RequirementType.totalMinutes,
    requirementValue: 1000,
    isUnlocked: (_, __, ___, totalMinutes, ____, _____, ______, _______, ________, _________, __________) => totalMinutes >= 1000,
    getProgress: (_, __, ___, totalMinutes, ____, _____, ______, _______, ________, _________, __________) => totalMinutes,
  ),
  AchievementDefinition(
    id: 'month_master',
    title: 'Month Master',
    description: 'Achieve a 30-day streak',
    icon: '🌙',
    tier: AchievementTier.gold,
    requirementType: RequirementType.currentStreak,
    requirementValue: 30,
    isUnlocked: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak >= 30,
    getProgress: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak,
  ),

  // Platinum tier
  AchievementDefinition(
    id: 'flow_expert',
    title: 'Flow Expert',
    description: 'Complete 50 sessions',
    icon: '🏆',
    tier: AchievementTier.platinum,
    requirementType: RequirementType.totalSessions,
    requirementValue: 50,
    isUnlocked: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions >= 50,
    getProgress: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions,
  ),
  AchievementDefinition(
    id: 'unstoppable',
    title: 'Unstoppable',
    description: 'Complete 50 tasks',
    icon: '💪',
    tier: AchievementTier.platinum,
    requirementType: RequirementType.totalTasks,
    requirementValue: 50,
    isUnlocked: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks >= 50,
    getProgress: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks,
  ),
  AchievementDefinition(
    id: 'legendary_streak',
    title: 'Legendary Streak',
    description: 'Achieve a 14-day streak',
    icon: '⚡',
    tier: AchievementTier.platinum,
    requirementType: RequirementType.currentStreak,
    requirementValue: 14,
    isUnlocked: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak >= 14,
    getProgress: (_, __, currentStreak, ___, ____, _____, ______, _______, ________, _________, __________) => currentStreak,
  ),
  AchievementDefinition(
    id: 'super_focus',
    title: 'Super Focus',
    description: 'Complete 100 sessions',
    icon: '🌟',
    tier: AchievementTier.platinum,
    requirementType: RequirementType.totalSessions,
    requirementValue: 100,
    isUnlocked: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions >= 100,
    getProgress: (totalSessions, _, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalSessions,
  ),
  AchievementDefinition(
    id: 'task_legend',
    title: 'Task Legend',
    description: 'Complete 100 tasks',
    icon: '👑',
    tier: AchievementTier.platinum,
    requirementType: RequirementType.totalTasks,
    requirementValue: 100,
    isUnlocked: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks >= 100,
    getProgress: (_, totalTasks, __, ___, ____, _____, ______, _______, ________, _________, __________) => totalTasks,
  ),
  AchievementDefinition(
    id: 'collection_king',
    title: 'Collection King',
    description: 'Unlock 10 achievements',
    icon: '👑',
    tier: AchievementTier.platinum,
    requirementType: RequirementType.achievementsUnlocked,
    requirementValue: 10,
    isUnlocked: (_, __, ___, ____, _____, ______, _______, ________, _________, __________, unlockedCount) => unlockedCount >= 10,
    getProgress: (_, __, ___, ____, _____, ______, _______, ________, _________, __________, unlockedCount) => unlockedCount,
  ),
];
